name: Android Build - Simple Signing

on:
  push:
    branches:
      - main  # Ganti sesuai branch utama kamu
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Make make.sh Executable
      # Memastikan skrip memiliki izin eksekusi
      run: chmod +x make.sh

    - name: Run make.sh keygen
      # Menjalankan skrip untuk membuat keystore (my-release-key.jks) 
      # yang akan digunakan oleh build.gradle.
      run: ./make.sh keygen

    - name: Get project path
      id: get-path
      # Proyek berada di sub-direktori 'app'
      run: |
        echo "path=$(pwd)/app" >> $GITHUB_OUTPUT

    - name: Build Release (APK and AAB)
      # Menjalankan build Gradle. Konfigurasi signing akan diambil dari app/build.gradle.
      run: |
        ./gradlew assembleRelease bundleRelease
      working-directory: ${{ steps.get-path.outputs.path }}

    - name: Find Build Artifacts
      id: find-artifacts
      run: |
        # Mencari file APK dan AAB yang dihasilkan
        APK_PATH=$(find . -name "*.apk" -type f | grep "release" | head -n 1)
        AAB_PATH=$(find . -name "*.aab" -type f | grep "release" | head -n 1)
        
        echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT
        echo "aab_path=$AAB_PATH" >> $GITHUB_OUTPUT
      working-directory: ${{ steps.get-path.outputs.path }}/build

    - name: Upload APK Release
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: ${{ steps.find-artifacts.outputs.apk_path }}

    - name: Upload AAB Release
      uses: actions/upload-artifact@v4
      with:
        name: release-aab
        path: ${{ steps.find-artifacts.outputs.aab_path }}

    - name: Upload Keystore
      uses: actions/upload-artifact@v4
      with:
        name: keystore-file
        # Mengunggah keystore yang dibuat oleh make.sh keygen.
        # Nama file diambil dari build.gradle: my-release-key.jks
        path: my-release-key.jks
        # Catatan: Jika 'make.sh keygen' menyimpan file di sub-direktori, harap sesuaikan path di atas.
