name: Android Build - Final Version

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      # Mengatur Java Development Kit
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    # BARU: Langkah untuk menginstal Android SDK
    - name: Setup Android SDK
      # Menggunakan action khusus untuk menginstal tools Android
      uses: android-actions/setup-android@v3 
      with:
        # Menginstal versi yang sering digunakan dan stabil
        api-level: 33 
        # Memastikan Command Line Tools dan Build Tools tersedia
        build-tools: 33.0.0 

    - name: Make make.sh Executable
      # Memberikan izin eksekusi
      run: chmod +x make.sh

    - name: Run make.sh keygen
      # Sekarang skrip ini seharusnya dapat menemukan Android tools
      run: ./make.sh keygen

    - name: Get Project Root Path
      id: get-root-path
      run: |
        echo "ROOT_DIR=$(pwd)" >> $GITHUB_ENV
        echo "APP_DIR=$(pwd)/app" >> $GITHUB_ENV

    - name: Build Release (APK and AAB)
      # Menjalankan build Gradle
      run: |
        ./gradlew assembleRelease bundleRelease
      working-directory: ${{ env.APP_DIR }}

    - name: Find Build Artifacts
      id: find-artifacts
      run: |
        BUILD_DIR="${{ env.APP_DIR }}/build"
        APK_PATH=$(find "$BUILD_DIR" -name "*.apk" -type f | grep "release" | head -n 1)
        AAB_PATH=$(find "$BUILD_DIR" -name "*.aab" -type f | grep "release" | head -n 1)
        
        echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT
        echo "aab_path=$AAB_PATH" >> $GITHUB_OUTPUT

    - name: Upload Keystore
      uses: actions/upload-artifact@v4
      with:
        name: keystore-file
        path: ${{ env.ROOT_DIR }}/my-release-key.jks

    - name: Upload APK Release
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: ${{ steps.find-artifacts.outputs.apk_path }}

    - name: Upload AAB Release
      uses: actions/upload-artifact@v4
      with:
        name: release-aab
        path: ${{ steps.find-artifacts.outputs.aab_path }}
